### ISSUE TITLE
Scheduler worker in group main failed with an uncaught exception

### ISSUE THREAD

**Issue by suning4583** [weixiaohui-1/nacos-consul-adapter#1]
Scheduler worker in group main failed with an uncaught exception

![image](https://user-images.githubusercontent.com/12489065/126808615-bff61c3c-b5bd-4775-86b8-07f4195954aa.png)

**Comment by chen-gliu** [comment]
Could you provide steps to reproduce the problem

**Comment by chen-gliu** [comment]
> Scheduler worker in group main failed with an uncaught exception
> 
> ![image](https://user-images.githubusercontent.com/12489065/126808615-bff61c3c-b5bd-4775-86b8-07f4195954aa.png)

A stack trace alone isn't very helpful. Can you provide your configuration and steps to reproduce the problem? @suning4583

**Comment by suning4583** [comment]
com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2021.1
com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2021.1
com.alibaba.nacos:nacos-client:2.0.0
org.springframework.cloud:spring-cloud-dependencies:2020.0.3
org.springframework.cloud:spring-cloud-starter-gateway:3.0.3
io.micrometer:micrometer-registry-prometheus:1.7.0

上面是主要的依赖

 - job_name: "dragon-gateway-prometheus"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["localhost:8881"]

上面是prometheus配置信息

启动服务会从nacos上面拉取工程配置文件，启动工程之长轮询模式获取服务信息，prometheus发送/v1/health/service 请求之后就出现上面的报错信息了

**Comment by chen-gliu** [comment]
com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2021.1的nacos client版本不是1.4.1吗？
我按照你给的依赖配置了一下，除了nacos client不是2.0，其他都一致，是可以正常使用的。
你看要不是使用nacos client 1.4.1再试一下。

**Comment by chen-gliu** [comment]
> Scheduler worker in group main failed with an uncaught exception
> 
> ![image](https://user-images.githubusercontent.com/12489065/126808615-bff61c3c-b5bd-4775-86b8-07f4195954aa.png)

@suning4583 我也尝试使用nacos 2.0.1客户端也是可以正常使用的。
<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-dependencies</artifactId>
			<version>2020.0.3</version>
			<type>pom</type>
			<scope>import</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.github.chen-gliu</groupId>
			<artifactId>nacos-consul-adapter</artifactId>
			<version>0.0.3.M</version>
		</dependency>

		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway</artifactId>
			<version>3.0.3</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<version>2021.1</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
			<version>2.0.1</version>
		</dependency>
	</dependencies>


以上是我测试使用的配置。
