### ISSUE TITLE
Whether nacos 2.X is supported

### ISSUE THREAD

**Issue by CrazyLionCat** [weixiaohui-1/nacos-consul-adapter#10]

**Comment by chen-gliu** [comment]
支持的

**Comment by CrazyLionCat** [comment]
> 支持的

会持续更新的嘛 挺你

**Comment by CrazyLionCat** [comment]
> 支持的

能否支持一下最新版本的 alibaba nacos

**Comment by CrazyLionCat** [comment]
> > 支持的
> 
> 能否支持一下最新版本的 alibaba nacos和boot

**Comment by CrazyLionCat** [comment]
https://github.com/chen-gliu/nacos-consul-adapter/pull/11 已提交pr

**Comment by CrazyLionCat** [comment]
还有个小提议 既然是监控 那么是否可以监控多个组的服务 实际生产中 多个组的需求还是很多的

**Comment by CrazyLionCat** [comment]
> 还有个小提议 既然是监控 那么是否可以监控多个组的服务 实际生产中 多个组的需求还是很多的

一般是不是得 在监控那边配不同组的网关

**Comment by chen-gliu** [comment]
有个配置我是写死的，是可以支持多套的。
