### ISSUE TITLE
springboot 配置了 server.servlet.context-path: xxxx 怎么

### ISSUE THREAD

**Issue by redtomatoL** [weixiaohui-1/nacos-consul-adapter#12]
target 获取的路径是这样的。都没有 context-path 。
![image](https://user-images.githubusercontent.com/28335333/205242530-b2a31a3b-e653-4df5-8a49-05539fc5c087.png)

实际暴露的监控端点为
![image](https://user-images.githubusercontent.com/28335333/205242839-b1d5ff99-84e2-4044-be34-a13f49e32bb0.png)

这个是我 prometheus.yml 的 配置
![image](https://user-images.githubusercontent.com/28335333/205243232-cc40aa13-d93c-45d7-b37c-07c1ac4f8fa5.png)

**Comment by chen-gliu** [comment]
你的问题是其他的服务都是down的吗
