### ISSUE TITLE
不支持Prometheus自定义打标签

### ISSUE THREAD

**Issue by BBdong** [weixiaohui-1/nacos-consul-adapter#13]
拉取微服务的lebles下的instance标签默认是内网ip+端口(见图)，后续alertmanager 告警通知只能获取当前服务的instance标签和job标签，获取不到当前告警服务的名称
![image](https://user-images.githubusercontent.com/36329283/206345041-0e9a2a39-0820-4bdb-99e0-195049850098.png)

**Comment by chen-gliu** [comment]
内网的ip是因为你使用nacos注册是内网ip，这个可以设置

**Comment by chen-gliu** [comment]
第二个告警不是服务的名称，这个应该和你的配置有关系

**Comment by BBdong** [comment]
其实就是想要这个效果(见图) ，  目前这个项目拉取的服务注册到Prometheus默认labels下只有job和instance(默认是ip+端口)   
如果是给注册的微服务动态打自定义标签目前还不支持    如图中的registerProjectName标签。  后续在告警时 可以使用诸如registerProjectName自定义标签去做一些事情 
![image](https://user-images.githubusercontent.com/36329283/206646813-42bb79a5-7c22-4c17-936a-03474315b3ec.png)

**Comment by BBdong** [comment]
我的做法是在Service类增加 Map<String, String> meta ， 然后把自定义标签放到meta 中 ， 然后再prometheus.yml中增加配置
    relabel_configs
       - regex: __meta_consul_service_metadata_(.+)
         action: labelmap

**Comment by BBdong** [comment]
如果可以我提交pull request， 加一些代码然后在READ.ME增加配置说明

**Comment by chen-gliu** [comment]
可以，欢迎

**Comment by chen-gliu** [comment]
我合并了，等有时间我更新一下版本

**Comment by xiohuchi** [comment]
这个不错
