### ISSUE TITLE
nacos discovery 2.2.1不支持

### ISSUE THREAD

**Issue by huangyaohai** [weixiaohui-1/nacos-consul-adapter#17]
nacos discovery 2.2.1不支持，报以下错，而readme里面写了，2.2+, 不严谨
java.lang.IllegalStateException: Failed to introspect Class [io.github.chengliu.nacosconsuladapter.NacosConsulAdapterConfig] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.2.7.RELEASE.jar:5.2.7.RELEASE]

**Comment by chen-gliu** [comment]
不会啊，我有时间试试

**Comment by chen-gliu** [comment]
我刚刚试了一下2.2.1确实不支持，我修改了说明，感谢提交issue

**Comment by chen-gliu** [comment]
![image](https://github.com/weixiaohui-1/nacos-consul-adapter/assets/30383620/13b4211d-01aa-42b1-9815-ac692311aef9)
时间太久了。。。有一个支持2.2.0的版本。。。
