### ISSUE TITLE
服务有context-path如何解决？

### ISSUE THREAD

**Issue by alang124** [weixiaohui-1/nacos-consul-adapter#19]

**Comment by chen-gliu** [comment]
在Prometheus的配置上加上对应的context-path就好了

**Comment by weixiaohui-1** [comment]
好像不太行，这样好像只能保证我提供的接口是可以访问的，但是Prometheus访问不到metric

**Comment by alang124** [comment]
不同的服务context-path不一样啊？
metrics_path不是整个job的配置是一样吗
我现在有3个服务 
服务1  context-path是  /a
服务2  context-path是  /b
服务3  context-path是  /

我没弄明白应该怎么样配置

**Comment by alang124** [comment]
> 在Prometheus的配置上加上对应的context-path就好了

不同的服务context-path不一样啊？
metrics_path不是整个job的配置是一样吗
我现在有3个服务
服务1 context-path是 /a
服务2 context-path是 /b
服务3 context-path是 /

我没弄明白应该怎么样配置

**Comment by chen-gliu** [comment]
scrape_configs:
  - job_name: 'spring-cloud'
    consul_sd_configs:
      - server: '<consul-server>:<consul-port>'
        services: ['<service-name>']
    metrics_path: '/actuator/prometheus'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*
        action: keep
      - source_labels: [__address__, __meta_consul_service]
        target_label: __metrics_path__
        replacement: '/$2/actuator/prometheus'

你可以通过打标签的方式配置。将context path通过标签传到Prometheus，然后Prometheus将这个标签内容替换metrics_path。当然我这里的名称是随便设置的，你要根据你标签实际的名称修改这个配置哈。
