### ISSUE TITLE
server配置

### ISSUE THREAD

**Issue by szylmzs** [weixiaohui-1/nacos-consul-adapter#22]
server: 引入nacos-consul-adapter实例的ip+端口

只能配置ip形式的吗？
如果gateway是经过转发的二级目录呢，比如a.a.com/cloud/，需要怎么配置

**Comment by chen-gliu** [comment]
你是说Prometheus中的配置吗，那个没有限制

**Comment by szylmzs** [comment]
> 你是说Prometheus中的配置吗，那个没有限制

我试过了，server配置成二级目录的形式会有报错

**Comment by chen-gliu** [comment]
如果是Prometheus中的配置，那个我改不了，那个是consult的插件。

**Comment by szylmzs** [comment]
![image](https://github.com/weixiaohui-1/nacos-consul-adapter/assets/5236065/41aac91c-3a1c-4b1d-aa0b-5129f7d7463d)
日志是这样的 麻烦看看

**Comment by chen-gliu** [comment]
帮你查了一下，是可以用域名配置的
consul_sd_configs:
  - server: 'consul.example.com:8500'
    services: []

**Comment by szylmzs** [comment]
> 帮你查了一下，是可以用域名配置的 consul_sd_configs:
> 
> * server: 'consul.example.com:8500'
>   services: []

不只是域名，还有二级目录
server: 'a.a.com/cloud/' 类似这样

**Comment by chen-gliu** [comment]
这个应该是你们ng或者啥配置的吧，你再对应的地方设置好跳转路径就好了。原本是a.com/+我提供的接口，现在你要在你配置跳转的地方跳转到这个地址就可以了

**Comment by szylmzs** [comment]
> 这个应该是你们ng或者啥配置的吧，你再对应的地方设置好跳转路径就好了。原本是a.com/+我提供的接口，现在你要在你配置跳转的地方跳转到这个地址就可以了

好的 谢谢 我知道是哪里的问题了
