### ISSUE TITLE
BUG: 获取服务实例和订阅服务变更都没有指定 group，使用的是默认group

### ISSUE THREAD

**Issue by rocasx** [weixiaohui-1/nacos-consul-adapter#3]
## LongPollingRegistrationService#getServiceInstance()
获取服务实例没有指定group,且不可以配置

## NacosServiceCenter#subscribe()
订阅服务变更没指定group，且不可以变更

**Comment by chen-gliu** [comment]
@lyyblnl 感谢指出错误，这个问题已经在0.0.4.M版本中修复了。
