### ISSUE TITLE
[VOLUNTEER] 是否可以建立低版本alibaba-nacos维护分支.

### ISSUE THREAD

**Issue by ShawnJim** [weixiaohui-1/nacos-consul-adapter#7]
### 描述
我本地仓库建立了 [0.0.4.M-2.2.0.RELEASE](https://github.com/ShawnJim/nacos-consul-adapter/tree/0.0.4.M-2.2.0.RELEASE) 分支维护了`spring-cloud-starter-alibaba-nacos-discovery:2.2.0.RELEASE` 的适配。仓库是否有意向建立低版本的适配分支，如果有想法的话我可以提pr更新维护.

**Comment by chen-gliu** [comment]
欢迎提交pr

**Comment by ShawnJim** [comment]
> 欢迎提交pr

我的建议是主仓可以先建立对应版本的分支，这样我pr可以把代码直接推到对应版本的维护分支上，不会和主干分支冲突。 例如本次我维护的版本是`2.2.0.RELEASE`, 主仓可以创建名为 `0.0.4.M-2.2.0.RELEASE` 的分支方便贡献者推送维护。

**Comment by chen-gliu** [comment]
推送了新的分支，0.0.5.M-2.2.0.RELEASE

**Comment by chen-gliu** [comment]
提交的什么注明最低支持到spring cloud什么版本，nacos是什么版本

**Comment by ShawnJim** [comment]
> 提交的什么注明最低支持到spring cloud什么版本，nacos是什么版本

已提交.

**Comment by chen-gliu** [comment]
我看你引入的nacos客户端版本是1.2，你nacos最低只支持到2.0.3?

**Comment by ShawnJim** [comment]
我描述问题， 我服务用的是2.0.3， 没做环境测试，保守就写了2.0.3.


发件人: chen
发送时间: 2022年6月27日 13:22
收件人: chen-gliu/nacos-consul-adapter
抄送: Shawn Jim; Author
主题: Re: [chen-gliu/nacos-consul-adapter] [VOLUNTEER] 是否可以建立低版本alibaba-nacos维护分支. (Issue #7)

我看你引入的nacos客户端版本是1.2，你nacos最低只支持到2.0.3?

**Comment by ShawnJim** [comment]
> 我看你引入的nacos客户端版本是1.2，你nacos最低只支持到2.0.3?

我晚点看下客户端支持版本，再更新下PR描述， 但是这个分支对应支持的版本描述最终你是想写在readme中？ 是的话我晚点一并给他加上。

**Comment by chen-gliu** [comment]
嗯，会写在里面。

**Comment by ShawnJim** [comment]
好的，我晚点一并更新。

发件人: chen
发送时间: 2022年6月27日 15:09
收件人: chen-gliu/nacos-consul-adapter
抄送: Shawn Jim; Author
主题: Re: [chen-gliu/nacos-consul-adapter] [VOLUNTEER] 是否可以建立低版本alibaba-nacos维护分支. (Issue #7)

➢ 嗯，会写在里面。

**Comment by ShawnJim** [comment]
已添加版本描述指引并更新PR.

**Comment by chen-gliu** [comment]
我先把你的提交merge了，最近有点忙，后面再看。

**Comment by ShawnJim** [comment]
> 我先把你的提交merge了，最近有点忙，后面再看。

好的

**Comment by ShawnJim** [comment]
好的， 我晚点一并更新。

发件人: chen
发送时间: 2022年6月27日 15:09
收件人: chen-gliu/nacos-consul-adapter
抄送: Shawn Jim; Author
主题: Re: [chen-gliu/nacos-consul-adapter] [VOLUNTEER] 是否可以建立低版本alibaba-nacos维护分支. (Issue #7)

➢ 嗯，会写在里面。
