### ISSUE TITLE
关于ipv6的问题

### ISSUE THREAD

**Issue by laoxiaokang** [weixiaohui-1/nacos-consul-adapter#9]
我的nacos-consul-adapter地址和springcloud服务地址都改成了ipv6的格式注册到nacos中，
![bb4b7c2b5732f2263d130c82716dcac](https://user-images.githubusercontent.com/45983816/189058025-7314ee73-a12f-47e0-8048-9029a2dc6bfa.jpg)
但是prometheus中的请求地址好像多了个[] ,导致prometheus请求不到数据，求老哥指点

**Comment by laoxiaokang** [comment]
@chen-gliu

**Comment by laoxiaokang** [comment]
我尝试在设置NODE的address时去掉'[]',但服务起来后，prometheus报了另外的错：
dial tcp [2409:807c:5a00:1060::54]:8788: connect: network is unreachable

**Comment by chen-gliu** [comment]
ipv6倒是没有试过，prometheus支持ipv6请求吗

**Comment by laoxiaokang** [comment]
今天修改了一下prometheus的network就可以了，prometheus是支持ipv6的；

**Comment by chen-gliu** [comment]
你这个是自己测试玩，还是你们公司就是用的ipv6

**Comment by laoxiaokang** [comment]
如果是ipv6,NODE地址需要去掉‘[]’,不然注册进prometheus时会出现上面的双括号问题

**Comment by laoxiaokang** [comment]
我们的正式环境有的服务用的是ipv6，之前没试过，也是刚用到

**Comment by chen-gliu** [comment]
如果在生产用到了这个项目，方便提供公司信息登记一下吗
这个不是强制的，不方便也关系

**Comment by laoxiaokang** [comment]
浪潮通信

**Comment by chen-gliu** [comment]
牛的，老哥
